### ISSUE TITLE
IMPORTANT 

### ISSUE THREAD

**Issue by adityatrips** [adityatrips/spotify-video-downloader#1]
Please note that your github account is logged in E3 3LA3.
Think of us as your well wishers, we will not hack your account but rather sign it out. We are not abusing this system, but someone else might.
Please make sure to log out of your accounts from labs after use.
Regards, 
- fellow human.

**Comment by NebulaTris** [comment]
Join us at http://asetalias.in .
  • Fellow GitHub User.
